services:
  backend:
    build: .
    ports:
      - "5000:3000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: thuan123
      MYSQL_USER: thuan123
      MYSQL_PASSWORD: thuan123
      MYSQL_ROOT_PASSWORD: thuan123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 10

volumes:
  db_data:
