version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5000:3000"         # Map port 5000 của VPS ra port 3000 trong container
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: thuan123
      MYSQL_USER: thuan123
      MYSQL_PASSWORD: thuan123
      MYSQL_ROOT_PASSWORD: thuan123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
